import React from 'react';

// Helper for hex colors to avoid Tailwind's oklch which html2canvas 1.4.1 doesn't support
const colors = {
  white: '#ffffff',
  gray50: '#f9fafb',
  gray100: '#f3f4f6',
  gray200: '#e5e7eb',
  gray300: '#d1d5db',
  gray400: '#9ca3af',
  gray500: '#6b7280',
  gray600: '#4b5563',
  gray800: '#1f2937',
  gray900: '#111827',
  blue50: '#eff6ff',
  blue500: '#3b82f6',
  blue800: '#1e40af',
  green50: '#f0fdf4',
  green500: '#22c55e',
  green800: '#166534',
  yellow50: '#fefce8',
  red50: '#fef2f2',
  red500: '#ef4444',
  red800: '#991b1b',
};

const VisualRenderer = ({ template, content, innerRef }) => {
  const data = content || {};

  // Common styles
  const baseStyle = { fontFamily: 'sans-serif', backgroundColor: colors.white, minWidth: '800px', boxSizing: 'border-box' };
  const h1Style = { fontSize: '36px', fontWeight: 'bold', color: colors.gray900, marginBottom: '8px', borderBottom: `2px solid ${colors.gray200}`, paddingBottom: '16px' };
  const h2Style = { fontSize: '30px', fontWeight: 'bold', textAlign: 'center', marginBottom: '24px', color: colors.gray900 };
  const h3Style = { fontSize: '20px', fontWeight: 'bold', marginBottom: '12px', color: colors.gray800 };
  const pStyle = { fontSize: '16px', color: colors.gray800, whiteSpace: 'pre-wrap' };
  const cardStyle = { padding: '24px', borderRadius: '8px', border: `1px solid ${colors.gray200}`, backgroundColor: colors.gray50, marginBottom: '24px' };

  // Note: Avoid 'shadow' classes from Tailwind as they use oklch in v4. Use manual box-shadow if needed.
  const shadowStyle = `0 4px 6px -1px ${colors.gray300}`;

  // --- Empathy Map Layout ---
  if (template.title === 'Empathy Map') {
    return (
      <div ref={innerRef} style={{ ...baseStyle, padding: '32px', minHeight: '600px' }}>
        <h2 style={h2Style}>{template.title}</h2>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', minHeight: '600px', border: `2px solid ${colors.gray800}`, position: 'relative' }}>


          {/* SAYS (Top Left) - NOW PARENT OF USER CIRCLE */}
          <div style={{ padding: '16px', backgroundColor: colors.yellow50, borderBottom: `2px solid ${colors.gray800}`, borderRight: `2px solid ${colors.gray800}`, position: 'relative' }}>
            <h3 style={{ ...h3Style, textAlign: 'center', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Says</h3>
            <p style={pStyle}>{data.says || data.ays || ''}</p>

            {/* User Circle anchored to bottom-right of this cell (the intersection) */}
            <div style={{
              position: 'absolute', bottom: '-1px', right: '-1px', transform: 'translate(50%, 50%)',
              zIndex: 10, width: '96px', height: '96px', borderRadius: '50%',
              backgroundColor: colors.white, border: `2px solid ${colors.gray800}`,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              boxShadow: shadowStyle
            }}>
              <span style={{ fontWeight: 'bold', fontSize: '18px', color: colors.gray900 }}>USER</span>
            </div>
          </div>

          {/* THINKS */}
          <div style={{ padding: '16px', backgroundColor: colors.blue50, borderBottom: `2px solid ${colors.gray800}` }}>
            <h3 style={{ ...h3Style, textAlign: 'center', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Thinks</h3>
            <p style={pStyle}>{data.thinks || ''}</p>
          </div>

          {/* DOES */}
          <div style={{ padding: '16px', backgroundColor: colors.green50, borderRight: `2px solid ${colors.gray800}` }}>
            <h3 style={{ ...h3Style, textAlign: 'center', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Does</h3>
            <p style={pStyle}>{data.does || ''}</p>
          </div>

          {/* FEELS */}
          <div style={{ padding: '16px', backgroundColor: colors.red50 }}>
            <h3 style={{ ...h3Style, textAlign: 'center', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Feels</h3>
            <p style={pStyle}>{data.feels || ''}</p>
          </div>
        </div>
        <div style={{ marginTop: '48px', paddingTop: '16px', borderTop: `1px solid ${colors.gray200}`, textAlign: 'center', fontSize: '14px', color: colors.gray400 }}>
          Generated by Design Thinking Platform
        </div>
      </div>
    );
  }

  // --- User Persona Layout ---
  if (template.title === 'User Persona') {
    return (
      <div ref={innerRef} style={{ ...baseStyle, padding: '32px' }}>
        <div style={{ padding: '24px', borderRadius: '8px', border: `4px solid ${colors.gray800}`, backgroundColor: colors.gray50 }}>
          <div style={{ display: 'flex', gap: '32px', marginBottom: '32px' }}>
            <div style={{
              width: '128px', height: '128px', borderRadius: '50%', flexShrink: 0,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: '36px', fontWeight: 'bold', backgroundColor: colors.gray300,
              color: colors.gray500, border: `2px solid ${colors.gray600}`
            }}>
              {(data.name || 'User').charAt(0).toUpperCase()}
            </div>
            <div style={{ flex: 1 }}>
              <h1 style={{ fontSize: '36px', fontWeight: 'bold', marginBottom: '8px', color: colors.gray900 }}>{data.name || 'Persona Name'}</h1>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', fontSize: '14px', padding: '16px', borderRadius: '4px', backgroundColor: colors.white, border: `1px solid ${colors.gray200}` }}>
                <div style={{ color: colors.gray800 }}><strong>Age:</strong> {data.age || 'N/A'}</div>
                <div style={{ color: colors.gray800 }}><strong>Gender:</strong> {data.gender || 'N/A'}</div>
                <div style={{ color: colors.gray800 }}><strong>Occupation:</strong> {data.occupation || 'N/A'}</div>
                <div style={{ color: colors.gray800 }}><strong>Location:</strong> {data.location || 'N/A'}</div>
              </div>
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '32px' }}>
            <div style={{ padding: '24px', borderRadius: '4px', backgroundColor: colors.white, borderLeft: `4px solid ${colors.blue500}`, boxShadow: '0 1px 2px 0 rgba(0,0,0,0.05)' }}>
              <h3 style={{ ...h3Style, color: colors.blue800 }}>Bio</h3>
              <p style={pStyle}>{data.bio || ''}</p>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
              <div style={{ padding: '24px', borderRadius: '4px', backgroundColor: colors.white, borderLeft: `4px solid ${colors.green500}`, boxShadow: '0 1px 2px 0 rgba(0,0,0,0.05)' }}>
                <h3 style={{ ...h3Style, color: colors.green800 }}>Goals</h3>
                <p style={pStyle}>{data.goals || ''}</p>
              </div>
              <div style={{ padding: '24px', borderRadius: '4px', backgroundColor: colors.white, borderLeft: `4px solid ${colors.red500}`, boxShadow: '0 1px 2px 0 rgba(0,0,0,0.05)' }}>
                <h3 style={{ ...h3Style, color: colors.red800 }}>Pain Points</h3>
                <p style={pStyle}>{data.painPoints || ''}</p>
              </div>
            </div>
          </div>
        </div>
        <div style={{ marginTop: '48px', paddingTop: '16px', borderTop: `1px solid ${colors.gray200}`, textAlign: 'center', fontSize: '14px', color: colors.gray400 }}>
          Generated by Design Thinking Platform
        </div>
      </div>
    );
  }

  // --- Questionnaire Layout ---
  if (template.title === 'Questionnaire') {
    const questions = data.questions ? data.questions.split('\n').filter(q => q.trim() !== '') : [];

    return (
      <div ref={innerRef} style={{ ...baseStyle, padding: '48px' }}>
        <h1 style={h1Style}>{template.title}</h1>

        <div style={{ padding: '24px', backgroundColor: colors.white, border: `1px solid ${colors.gray200}`, borderRadius: '8px', boxShadow: shadowStyle, marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '16px' }}>
             <h3 style={{ ...h3Style, marginBottom: '0', width: 'auto' }}>User Type:</h3>
             <p style={{ ...pStyle, margin: 0 }}>{data.userType || <span style={{ fontStyle: 'italic', color: colors.gray400 }}>Not defined.</span>}</p>
        </div>

        <div style={{ padding: '32px', backgroundColor: colors.white, border: `1px solid ${colors.gray200}`, borderRadius: '8px', boxShadow: shadowStyle }}>
          <h3 style={{ ...h3Style, marginBottom: '24px', borderBottom: `1px solid ${colors.gray200}`, paddingBottom: '16px' }}>Research Questions</h3>
          {data.questions ? (
            <div style={{ fontSize: '16px', color: colors.gray800, whiteSpace: 'pre-wrap', lineHeight: '1.625' }}>
              {data.questions}
            </div>
          ) : (
            <p style={{ fontStyle: 'italic', color: colors.gray400 }}>No questions added yet.</p>
          )}
        </div>
        <div style={{ marginTop: '48px', paddingTop: '16px', borderTop: `1px solid ${colors.gray200}`, textAlign: 'center', fontSize: '14px', color: colors.gray400 }}>
          Generated by Design Thinking Platform
        </div>
      </div>
    );
  }

  // --- How Might We Questions Layout ---
  if (template.title === 'How Might We Questions') {
    const questions = data.questions ? data.questions.split('\n').filter(q => q.trim() !== '') : [];

    return (
      <div ref={innerRef} style={{ ...baseStyle, padding: '48px' }}>
        <h1 style={h1Style}>{template.title}</h1>

        {/* Core Problem Section */}
        <div style={{ padding: '32px', backgroundColor: colors.white, border: `1px solid ${colors.gray200}`, borderRadius: '8px', marginBottom: '32px', boxShadow: shadowStyle }}>
          <h3 style={{ ...h3Style, marginBottom: '16px' }}>Core Problem</h3>
          <p style={{ ...pStyle, fontSize: '16px', lineHeight: '1.6' }}>{data.problem || <span style={{ fontStyle: 'italic', color: colors.gray400 }}>No problem defined.</span>}</p>
        </div>

        {/* Questions List */}
        <div style={{ padding: '32px', backgroundColor: colors.white, border: `1px solid ${colors.gray200}`, borderRadius: '8px', boxShadow: shadowStyle }}>
          <h3 style={{ ...h3Style, marginBottom: '24px', borderBottom: `1px solid ${colors.gray200}`, paddingBottom: '16px' }}>Questions</h3>
          {questions.length > 0 ? (
            <ul style={{ listStyleType: 'none', padding: 0, margin: 0 }}>
              {questions.map((q, idx) => (
                <li key={idx} style={{
                  marginBottom: '16px',
                  padding: '16px',
                  backgroundColor: idx % 2 === 0 ? colors.gray50 : colors.white,
                  borderLeft: `4px solid ${colors.purple500}`,
                  borderRadius: '4px',
                  fontSize: '16px',
                  color: colors.gray800
                }}>
                  {q}
                </li>
              ))}
            </ul>
          ) : (
            <p style={{ fontStyle: 'italic', color: colors.gray400 }}>No questions added yet.</p>
          )}
        </div>
        <div style={{ marginTop: '48px', paddingTop: '16px', borderTop: `1px solid ${colors.gray200}`, textAlign: 'center', fontSize: '14px', color: colors.gray400 }}>
          Generated by Design Thinking Platform
        </div>
      </div>
    );
  }

  // --- Idea Categorization (Board Layout) ---
  if (template.title === 'Idea Categorization') {
    const categories = data.categories || [];

    return (
      <div ref={innerRef} style={{ ...baseStyle, padding: '32px' }}>
        <h1 style={h1Style}>{template.title}</h1>

        <div style={{ display: 'flex', gap: '24px', alignItems: 'flex-start' }}>
          {categories.filter(c => c.items.length > 0 || c.id !== 'uncategorized').map(cat => (
            <div key={cat.id} style={{
              flex: '1',
              minWidth: '200px',
              padding: '16px',
              borderRadius: '8px',
              backgroundColor: colors.gray100,
              border: `1px solid ${colors.gray200}`
            }}>
              <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '16px', color: colors.gray700 }}>{cat.title}</h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                {cat.items.map(item => (
                  <div key={item.id} style={{
                    padding: '12px',
                    backgroundColor: '#fef3c7', // yellow-200
                    border: '1px solid #fde047', // yellow-300
                    borderRadius: '4px',
                    fontSize: '14px',
                    color: colors.gray900,
                    whiteSpace: 'pre-wrap',
                    wordBreak: 'break-word'
                  }}>
                    {item.content}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
        <div style={{ marginTop: '48px', paddingTop: '16px', borderTop: `1px solid ${colors.gray200}`, textAlign: 'center', fontSize: '14px', color: colors.gray400 }}>
          Generated by Design Thinking Platform
        </div>
      </div>
    );
  }

  // --- User Journey Map Table Layout ---
  if (template.title === 'User Journey Map') {
    const grid = data.grid || {};
    const STAGES = ['Awareness', 'Consideration', 'Decision', 'Service', 'Loyalty'];
    const ROWS = [
      'Customer Actions',
      'Touchpoints',
      'Customer Experience',
      'Pain Points',
      'KPIs',
      'Business Goals',
      'Team(s) Involved'
    ];

    // Light pastel colors for rows
    const ROW_COLORS = {
      'Customer Actions': '#fff7ed', // orange-50
      'Touchpoints': '#eff6ff', // blue-50
      'Customer Experience': '#f0fdf4', // green-50
      'Pain Points': '#fef2f2', // red-50
      'KPIs': '#faf5ff', // purple-50
      'Business Goals': '#ecfeff', // cyan-50
      'Team(s) Involved': '#fdf4ff' // fuchsia-50
    };

    return (
      <div ref={innerRef} style={{ ...baseStyle, padding: '32px' }}>
        <h1 style={h1Style}>{template.title}</h1>

        <div style={{ width: '100%' }}>
          <table style={{
            width: '100%',
            borderCollapse: 'collapse',
            border: `1px solid ${colors.gray300}`,
            fontSize: '14px'
          }}>
            <thead>
              <tr>
                <th style={{
                  border: `1px solid ${colors.gray300}`,
                  padding: '12px',
                  backgroundColor: colors.gray100,
                  textAlign: 'left',
                  width: '200px',
                  fontWeight: 'bold',
                  color: colors.gray800
                }}>Stage</th>
                {STAGES.map(stage => (
                  <th key={stage} style={{
                    border: `1px solid ${colors.gray300}`,
                    padding: '12px',
                    backgroundColor: '#eff6ff',
                    color: '#1e3a8a',
                    fontWeight: 'bold'
                  }}>
                    {stage}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {ROWS.map(row => (
                <tr key={row}>
                  <td style={{
                    border: `1px solid ${colors.gray300}`,
                    padding: '12px',
                    backgroundColor: colors.gray50,
                    fontWeight: '600',
                    color: colors.gray800
                  }}>
                    {row}
                  </td>
                  {STAGES.map(stage => (
                    <td key={stage} style={{
                      border: `1px solid ${colors.gray300}`,
                      padding: '12px',
                      backgroundColor: ROW_COLORS[row] || '#ffffff',
                      color: colors.gray900,
                      verticalAlign: 'top',
                      whiteSpace: 'pre-wrap'
                    }}>
                      {grid[row]?.[stage] || ''}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div style={{ marginTop: '48px', paddingTop: '16px', borderTop: `1px solid ${colors.gray200}`, textAlign: 'center', fontSize: '14px', color: colors.gray400 }}>
          Generated by Design Thinking Platform
        </div>
      </div>
    );
  }


  // --- Paper Prototypes Layout ---
  if (template.title === 'Paper Prototypes') {
    // NOTE: For full fidelity export, we might want to capture the actual ReactFlow instance.
    // However, since VisualRenderer is used for the "Preview" pane *and* the hidden export container,
    // we can try to render the nodes visually here, or (simpler) just rely on the Editor's view for export 
    // if we change how export works. 
    // FOR NOW: We will replicate a simple visual representation of the nodes without React Flow interaction,
    // to ensure it renders in the export container.

    const nodes = data.nodes || [];
    const edges = data.edges || [];

    // 1. Calculate bounding box to normalize positions (prevent overlap with title)
    let minX = Infinity;
    let minY = Infinity;
    let maxBottom = 0;

    if (nodes.length > 0) {
      nodes.forEach(node => {
        if (node.position.x < minX) minX = node.position.x;
        if (node.position.y < minY) minY = node.position.y;
      });
    } else {
      minX = 0;
      minY = 0;
    }

    // Add a margin buffer (e.g., 20px) to the normalized positions
    const BUFFER = 20;

    // Helper: Get Normalized Position
    const getNormPos = (pos) => ({
      x: pos.x - minX + BUFFER,
      y: pos.y - minY + BUFFER
    });

    // Helper to get node center (using normalized positions)
    const getNodeCenter = (node) => {
      if (!node) return { x: 0, y: 0 };
      const pos = getNormPos(node.position);

      let w = 0;
      let h = 0;

      if (node.type === 'prototype') {
        w = 288;
        h = 400; // Estimate
      } else if (node.type === 'note') {
        // Robust width/height check
        // 1. Try style.width (string or number)
        // 2. Try node.measured?.width or node.width
        // 3. Fallback
        const checkWidth = node.style?.width ?? node.measured?.width ?? node.width;
        const checkHeight = node.style?.height ?? node.measured?.height ?? node.height;

        w = checkWidth ? parseInt(checkWidth) : 200;
        h = checkHeight ? parseInt(checkHeight) : 150;
      }

      return {
        x: pos.x + w / 2,
        y: pos.y + h / 2
      };
    };

    const nodeMap = new Map(nodes.map(n => [n.id, n]));

    // Calculate container dimensions
    let contentMaxBottom = 0;
    let maxRight = 0;

    nodes.forEach(node => {
      const pos = getNormPos(node.position);

      // Calculate Height
      let h = 200;
      if (node.type === 'prototype') h = 500;
      else {
        const checkHeight = node.style?.height ?? node.measured?.height ?? node.height;
        h = checkHeight ? parseInt(checkHeight) : 150;
      }
      const bottom = pos.y + h;
      if (bottom > contentMaxBottom) contentMaxBottom = bottom;

      // Calculate Width to fix background cutoff
      let w = 300;
      if (node.type === 'prototype') {
        w = 300;
      } else {
        const checkWidth = node.style?.width ?? node.measured?.width ?? node.width;
        w = checkWidth ? parseInt(checkWidth) : 200;
      }
      const right = pos.x + w;
      if (right > maxRight) maxRight = right;
    });

    // Ensure min dimensions with generous margins
    const containerHeight = Math.max(800, contentMaxBottom + 200);
    const containerWidth = Math.max(1200, maxRight + 200); // Default to at least 1200px wide

    const getArrowHead = (x1, y1, x2, y2) => {
      // Calculate angle
      const angle = Math.atan2(y2 - y1, x2 - x1);
      const headLen = 10;

      // Points for a simple arrowhead triangle
      // Tip at x2, y2
      // Wings back by headLen

      // To rotate:
      // x' = x*cos - y*sin
      // y' = x*sin + y*cos

      // Back point on line:
      const bx = x2 - headLen * Math.cos(angle);
      const by = y2 - headLen * Math.sin(angle);

      // Perpendicular offset for width
      const width = 6;
      const px = width * Math.cos(angle + Math.PI / 2);
      const py = width * Math.sin(angle + Math.PI / 2);

      const p1x = bx + px;
      const p1y = by + py;

      const p2x = bx - px;
      const p2y = by - py;

      return `${x2},${y2} ${p1x},${p1y} ${p2x},${p2y}`;
    };

    return (
      <div ref={innerRef} style={{
        ...baseStyle,
        padding: '32px',
        height: `${containerHeight}px`,
        width: `${containerWidth}px`, // Explicit width to force background coverage
        position: 'relative',
        backgroundColor: '#f8fafc'
      }}>
        <h1 style={h1Style}>{template.title}</h1>

        <div style={{ position: 'relative', width: '100%', height: '100%' }}>
          {/* Edges Layer (SVG) */}
          <svg style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', pointerEvents: 'none', zIndex: 0 }}>
            {edges.map(edge => {
              const sourceNode = nodeMap.get(edge.source);
              const targetNode = nodeMap.get(edge.target);
              if (!sourceNode || !targetNode) return null;

              const start = getNodeCenter(sourceNode);
              const end = getNodeCenter(targetNode);

              return (
                <g key={edge.id}>
                  {/* Edge Line */}
                  <line
                    x1={start.x} y1={start.y}
                    x2={end.x} y2={end.y}
                    stroke={colors.gray400}
                    strokeWidth="2"
                  />

                  {/* Manual Arrowhead */}
                  <polygon
                    points={getArrowHead(start.x, start.y, end.x, end.y)}
                    fill={colors.gray400}
                  />
                </g>
              );
            })}
          </svg>

          {/* Edge HTML Labels Layer - Overlays on top of Lines but below nodes */}
          {edges.map(edge => {
            const sourceNode = nodeMap.get(edge.source);
            const targetNode = nodeMap.get(edge.target);
            const label = edge.data?.label;
            
            if (!sourceNode || !targetNode || !label) return null;

            const start = getNodeCenter(sourceNode);
            const end = getNodeCenter(targetNode);
            const midX = (start.x + end.x) / 2;
            const midY = (start.y + end.y) / 2;

            return (
              <div key={`label-${edge.id}`} style={{
                position: 'absolute',
                left: midX,
                top: midY,
                transform: 'translate(-50%, -50%)',
                backgroundColor: colors.white,
                padding: '4px 8px',
                borderRadius: '4px',
                border: `1px solid ${colors.gray300}`,
                color: colors.gray800,
                fontSize: '12px',
                fontWeight: '500',
                whiteSpace: 'nowrap',
                boxShadow: '0 1px 2px rgba(0,0,0,0.1)',
                zIndex: 5
              }}>
                {label}
              </div>
            );
          })}

          {/* Nodes Layer */}
          {nodes.map(node => {
            const pos = getNormPos(node.position);

            if (node.type === 'prototype') {
              return (
                <div key={node.id} style={{
                  position: 'absolute',
                  left: pos.x,
                  top: pos.y,
                  width: '288px', // w-72
                  border: `2px solid ${colors.gray200}`,
                  borderRadius: '8px',
                  backgroundColor: colors.white,
                  boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
                  zIndex: 10
                }}>
                  {/* Header */}
                  <div style={{ padding: '8px', borderBottom: `1px solid ${colors.gray200}`, backgroundColor: colors.gray50, display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ fontSize: '12px', fontWeight: 'bold', color: colors.gray500, textTransform: 'uppercase' }}>{node.data.screenType || 'Screen'}</span>
                  </div>
                  {/* Image */}
                  <div style={{ height: '160px', backgroundColor: colors.gray100, display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }}>
                    {node.data.image ? (
                      <img src={node.data.image} alt="Prototype" style={{ width: '100%', height: '100%', objectFit: 'contain' }} />
                    ) : (
                      <span style={{ color: colors.gray400, fontSize: '12px' }}>No Image</span>
                    )}
                  </div>
                  {/* Content */}
                  <div style={{ padding: '12px' }}>
                    <div style={{ fontWeight: 'bold', fontSize: '14px', marginBottom: '8px' }}>{node.data.title || 'Untitled'}</div>
                    <div style={{ display: 'flex', gap: '8px', fontSize: '12px', marginBottom: '8px' }}>
                      <span style={{ padding: '2px 4px', border: `1px solid ${colors.gray200}`, borderRadius: '4px' }}>{node.data.status || 'Draft'}</span>
                      {node.data.flowStep && <span style={{ padding: '2px 4px', border: `1px solid ${colors.gray200}`, borderRadius: '4px' }}>Step {node.data.flowStep}</span>}
                    </div>
                    {/* Fixed: Multiline description */}
                    <p style={{ fontSize: '12px', color: colors.gray600, whiteSpace: 'pre-wrap' }}>{node.data.description}</p>
                  </div>
                </div>
              );
            }
            if (node.type === 'note') {
              // Respect Resizing with robust check
              const checkWidth = node.style?.width ?? node.measured?.width ?? node.width;
              // Use height as minimum, allow expansion
              const checkHeight = node.style?.height ?? node.measured?.height ?? node.height;

              const w = checkWidth ? parseInt(checkWidth) : 200;
              const h = checkHeight ? parseInt(checkHeight) : 150;

              return (
                <div key={node.id} style={{
                  position: 'absolute',
                  left: pos.x,
                  top: pos.y,
                  width: `${w}px`, // Explicitly add px
                  minHeight: `${h}px`, // Ensure it starts at least this tall
                  height: 'auto', // Auto grow
                  padding: '16px',
                  borderRadius: '8px',
                  border: '1px solid #fef08a', // yellow-200
                  backgroundColor: '#fef9c3', // yellow-100
                  boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
                  zIndex: 10,
                  boxSizing: 'border-box'
                }}>
                  <div style={{ fontSize: '10px', textTransform: 'uppercase', fontWeight: 'bold', color: '#ca8a04', marginBottom: '8px' }}>Note</div>
                  <p style={{ fontSize: '14px', color: '#1f2937', whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>{node.data.label}</p>
                </div>
              );
            }
            return null;
          })}
        </div>
        <div style={{ marginTop: '48px', paddingTop: '16px', borderTop: `1px solid ${colors.gray200}`, textAlign: 'center', fontSize: '14px', color: colors.gray400 }}>
          Generated by Design Thinking Platform
        </div>
      </div>
    );
  }

  // --- Storyboarding Layout ---
  if (template.title === 'Storyboarding' || template.title === 'Storyboard') {
    const frames = data.frames || [];
    return (
      <div ref={innerRef} style={{ ...baseStyle, padding: '32px' }}>
        <h1 style={h1Style}>{template.title}</h1>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '32px' }}>
          {frames.map((frame, idx) => (
            <div key={frame.id || idx} style={{ border: `1px solid ${colors.gray200}`, borderRadius: '8px', overflow: 'hidden', backgroundColor: colors.white, breakInside: 'avoid' }}>
              {/* Image */}
              <div style={{ height: '300px', backgroundColor: colors.gray100, borderBottom: `1px solid ${colors.gray200}`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                {frame.image ? (
                  <img src={frame.image} alt={`Frame ${idx + 1}`} style={{ width: '100%', height: '100%', objectFit: 'contain' }} />
                ) : (
                  <span style={{ color: colors.gray400 }}>No Image</span>
                )}
              </div>
              {/* Content */}
              <div style={{ padding: '20px' }}>
                <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '12px', color: colors.gray800 }}>Frame {idx + 1}</h3>

                <div style={{ marginBottom: '16px' }}>
                  <strong style={{ display: 'block', fontSize: '12px', color: colors.gray500, textTransform: 'uppercase' }}>Context</strong>
                  <p style={{ ...pStyle, marginTop: '4px' }}>{frame.context}</p>
                </div>
                <div style={{ marginBottom: '16px' }}>
                  <strong style={{ display: 'block', fontSize: '12px', color: colors.gray500, textTransform: 'uppercase' }}>Action</strong>
                  <p style={{ ...pStyle, marginTop: '4px' }}>{frame.action}</p>
                </div>
                <div>
                  <strong style={{ display: 'block', fontSize: '12px', color: colors.gray500, textTransform: 'uppercase' }}>Outcome</strong>
                  <p style={{ ...pStyle, marginTop: '4px' }}>{frame.outcome}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
        <div style={{ marginTop: '48px', paddingTop: '16px', borderTop: `1px solid ${colors.gray200}`, textAlign: 'center', fontSize: '14px', color: colors.gray400 }}>
          Generated by Design Thinking Platform
        </div>
      </div>
    );
  }

  // --- Feedback Form Layout ---
  if (template.title === 'Feedback Form') {
    const items = data.items || [];
    return (
      <div ref={innerRef} style={{ ...baseStyle, padding: '48px' }}>
        <h1 style={h1Style}>{template.title}</h1>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
          {items.map((item, idx) => (
            <div key={item.id || idx} style={cardStyle}>
              <h3 style={{ ...h3Style, marginBottom: '8px' }}>
                <span style={{ fontSize: '12px', color: colors.gray500, textTransform: 'uppercase', marginRight: '8px' }}>Q{idx + 1}:</span>
                {item.question || <span style={{ fontStyle: 'italic', color: colors.gray400 }}>No Question</span>}
              </h3>
              <div style={{ padding: '16px', backgroundColor: colors.white, border: `1px solid ${colors.gray200}`, borderRadius: '4px' }}>
                <strong style={{ display: 'block', fontSize: '12px', color: colors.gray500, marginBottom: '4px' }}>ANSWER:</strong>
                <p style={{ ...pStyle, margin: 0 }}>{item.answer || <span style={{ fontStyle: 'italic', color: colors.gray400 }}>No Answer provided.</span>}</p>
              </div>
            </div>
          ))}
          {items.length === 0 && (
            <p style={{ fontStyle: 'italic', color: colors.gray500 }}>No feedback questions added.</p>
          )}
        </div>
        <div style={{ marginTop: '48px', paddingTop: '16px', borderTop: `1px solid ${colors.gray200}`, textAlign: 'center', fontSize: '14px', color: colors.gray400 }}>
          Generated by Design Thinking Platform
        </div>
      </div>
    );
  }

  // --- Business Model Canvas Layout ---
  if (template.title === 'Business Model Canvas') {
      const field = (key) => ((data[key] || '') + '').split('\n').map((line, i) => <div key={i}>{line}</div>);
      
      const cellStyle = {
          borderRight: '2px solid black',
          padding: '12px',
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden',
          backgroundColor: 'white',
          position: 'relative'
      };
      
      const labelStyle = {
          fontSize: '12px',
          fontWeight: 'bold',
          textTransform: 'uppercase',
          marginBottom: '8px',
          color: 'black',
          position: 'relative',
          zIndex: 10
      };
      
      const contentStyle = {
          fontSize: '14px',
          flexGrow: 1,
          whiteSpace: 'pre-wrap',
          wordWrap: 'break-word', // Fix overflow
          position: 'relative',
          zIndex: 10
      };

      const subSectionStyle = {
          marginTop: '16px',
          paddingTop: '8px',
          borderTop: '1px dashed #ccc',
          flexGrow: 1, 
          display: 'flex', 
          flexDirection: 'column',
          position: 'relative',
          zIndex: 10
      };

      // Watermark style removed for export as requested

      return (
        <div ref={innerRef} style={{ ...baseStyle, width: '2400px', padding: '32px', height: 'auto', minHeight: '900px', display: 'flex', flexDirection: 'column' }}>
          <h1 style={{ ...h1Style, marginBottom: '24px' }}>{template.title}</h1>
          
          <div style={{ border: '2px solid black', display: 'flex', flexDirection: 'column', minHeight: '1200px', backgroundColor: 'white' }}>
              {/* Top Section (Flexible height, min 67% approx visually) */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr 1fr', flexGrow: 2, borderBottom: '2px solid black' }}>
                  {/* 1. Problem */}
                  <div style={cellStyle}>
                      <div style={{ flexGrow: 1, display: 'flex', flexDirection: 'column' }}>
                        <div style={labelStyle}>Problem</div>
                        <div style={contentStyle}>{field('problem')}</div>
                      </div>
                      <div style={subSectionStyle}>
                         <div style={labelStyle}>Existing Alternatives</div>
                         <div style={contentStyle}>{field('existing-alternatives')}</div>
                      </div>
                  </div>

                  {/* 2. Solution & Metrics */}
                  <div style={{ display: 'flex', flexDirection: 'column', borderRight: '2px solid black' }}>
                      <div style={{ ...cellStyle, borderRight: 'none', flex: 1 }}>
                          <div style={labelStyle}>Solution</div>
                          <div style={contentStyle}>{field('solution')}</div>
                      </div>
                      <div style={{ ...cellStyle, borderRight: 'none', flex: 1, borderTop: '2px solid black' }}>
                          <div style={labelStyle}>Key Metrics</div>
                          <div style={contentStyle}>{field('key-metrics')}</div>
                      </div>
                  </div>

                  {/* 3. UVP */}
                  <div style={cellStyle}>
                      <div style={{ flexGrow: 1, display: 'flex', flexDirection: 'column' }}>
                        <div style={labelStyle}>Unique Value Proposition</div>
                        <div style={contentStyle}>{field('uvp')}</div>
                      </div>
                       <div style={subSectionStyle}>
                         <div style={labelStyle}>High-Level Concept</div>
                         <div style={contentStyle}>{field('high-level-concept')}</div>
                      </div>
                  </div>

                  {/* 4. Unfair Advantage & Channels */}
                  <div style={{ display: 'flex', flexDirection: 'column', borderRight: '2px solid black' }}>
                      <div style={{ ...cellStyle, borderRight: 'none', flex: 1 }}>
                          <div style={labelStyle}>Unfair Advantage</div>
                          <div style={contentStyle}>{field('unfair-advantage')}</div>
                      </div>
                      <div style={{ ...cellStyle, borderRight: 'none', flex: 1, borderTop: '2px solid black' }}>
                          <div style={labelStyle}>Channels</div>
                          <div style={contentStyle}>{field('channels')}</div>
                      </div>
                  </div>

                  {/* 5. Customer Segments */}
                  <div style={{ ...cellStyle, borderRight: 'none' }}>
                      <div style={{ flexGrow: 1, display: 'flex', flexDirection: 'column' }}>
                        <div style={labelStyle}>Customer Segments</div>
                        <div style={contentStyle}>{field('customer-segments')}</div>
                      </div>
                       <div style={subSectionStyle}>
                         <div style={labelStyle}>Early Adopters</div>
                         <div style={contentStyle}>{field('early-adopters')}</div>
                      </div>
                  </div>
              </div>

              {/* Bottom Section (Flexible height, min 33% approx visually) */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', flexGrow: 1 }}>
                  <div style={{ ...cellStyle, borderRight: '2px solid black' }}>
                      <div style={labelStyle}>Cost Structure</div>
                      <div style={contentStyle}>{field('cost-structure')}</div>
                  </div>
                  <div style={{ ...cellStyle, borderRight: 'none' }}>
                      <div style={labelStyle}>Revenue Streams</div>
                      <div style={contentStyle}>{field('revenue-streams')}</div>
                  </div>
              </div>
          </div>
        </div>
      );
  }

  // --- Service Blueprint Layout ---
  if (template.title === 'Service Blueprint') {
    // Data normalization: Support both old 'steps' (columns) and new 'rowItems' (independent rows)
    let rowItems = data.rowItems;
    if (!rowItems && data.steps) {
       // Migrate on the fly for display
       rowItems = { emotions: [], actions: [], touchpoints: [], frontstage: [], backstage: [], support: [] };
       data.steps.forEach(step => {
          ['emotions', 'actions', 'touchpoints', 'frontstage', 'backstage', 'support'].forEach(key => {
             if (step[key]) rowItems[key].push({ id: Math.random(), text: step[key] });
          });
       });
    }
    // Fallback if empty
    if (!rowItems) rowItems = { emotions: [], actions: [], touchpoints: [], frontstage: [], backstage: [], support: [] };

    const rows = [
      { id: 'emotions', label: 'Customer Emotions', bg: '#fb923c', border: '#fdba74', boxBg: '#ffedd5', boxBorder: '#fdba74', textColor: '#1f2937' }, // orange-400
      { id: 'actions', label: 'Customer Actions', bg: '#f97316', border: '#fdba74', boxBg: '#fed7aa', boxBorder: '#fdba74', textColor: '#1f2937' }, // orange-500
      { id: 'touchpoints', label: 'Touch Points', bg: '#fbbf24', border: '#fcd34d', boxBg: '#fde68a', boxBorder: '#fcd34d', textColor: '#1f2937' }, // amber-400
      { id: 'frontstage', label: 'Frontstage', bg: '#14b8a6', border: '#5eead4', boxBg: '#99f6e4', boxBorder: '#5eead4', textColor: '#1f2937' }, // teal-200
      { id: 'backstage', label: 'Backstage', bg: '#1d4ed8', border: '#60a5fa', boxBg: '#2563eb', boxBorder: '#60a5fa', textColor: '#ffffff' }, // blue-600
      { id: 'support', label: 'Support Processes', bg: '#6b21a8', border: '#a855f7', boxBg: '#581c87', boxBorder: '#a855f7', textColor: '#ffffff' }, // purple-900
    ];

    const separatorStyle = {
      backgroundColor: '#374151',
      color: 'white',
      fontSize: '12px',
      fontWeight: 'bold',
      padding: '4px 16px',
      textAlign: 'center',
      borderTop: '1px dashed white',
      borderBottom: '1px dashed white',
      lineHeight: '1',
      width: '100%'
    };

    return (
       <div ref={innerRef} style={{ ...baseStyle, padding: '32px', width: 'fit-content', minWidth: '1200px' }}>
          <h1 style={h1Style}>{template.title}</h1>
          <div style={{ display: 'flex', flexDirection: 'column', border: '1px solid #e5e7eb', boxShadow: shadowStyle }}>
             {rows.map(row => (
                <div key={row.id} style={{ display: 'flex', flexDirection: 'column' }}>
                   {/* Separators */}
                   {row.id === 'frontstage' && <div style={separatorStyle}>Line of Interaction</div>}
                   {row.id === 'backstage' && <div style={separatorStyle}>Line of Visibility</div>}
                   {row.id === 'support' && <div style={separatorStyle}>Line of Internal Interaction</div>}

                   <div style={{ display: 'flex', borderBottom: '1px solid #e5e7eb', minHeight: '150px' }}>
                     {/* Header */}
                     <div style={{ width: '200px', backgroundColor: row.bg, padding: '16px', color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', textAlign: 'center', flexShrink: 0 }}>
                        {row.label}
                     </div>
                     {/* Independent Items (Space Around) */}
                     <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'space-around', padding: '16px', backgroundColor: '#f9fafb' }}>
                        {(rowItems[row.id] || []).map((item, idx, arr) => (
                           <div key={item.id || idx} style={{ minWidth: '180px', maxWidth: '400px', position: 'relative', margin: '0 16px', flexShrink: 0 }}>
                              <div style={{ 
                                 padding: '12px', 
                                 backgroundColor: row.boxBg,
                                 border: `1px solid ${row.boxBorder}`,
                                 borderRadius: '4px',
                                 minHeight: row.id === 'backstage' || row.id === 'support' ? '128px' : '96px', // 8rem / 6rem approx
                                 fontSize: '14px',
                                 whiteSpace: 'pre-wrap',
                                 wordBreak: 'break-word',
                                 color: row.textColor
                              }}>
                                 {item.text}
                              </div>
                              {/* Arrow */}
                              {idx < arr.length - 1 && row.id !== 'emotions' && (
                                 <div style={{ position: 'absolute', right: '-24px', top: '50%', transform: 'translateY(-50%)', zIndex: 10, color: '#9ca3af', fontSize: '20px' }}>
                                    →
                                 </div>
                              )}
                           </div>
                        ))}
                        {(rowItems[row.id] || []).length === 0 && (
                           <div style={{ color: '#9ca3af', fontStyle: 'italic', fontSize: '14px' }}>No items</div>
                        )}
                     </div>
                   </div>
                </div>
             ))}
          </div>
          <div style={{ marginTop: '48px', paddingTop: '16px', borderTop: `1px solid ${colors.gray200}`, textAlign: 'center', fontSize: '14px', color: colors.gray400 }}>
             Generated by Design Thinking Platform
          </div>
       </div>
    );
  }

  // --- Mind Mapping Layout ---
  if (template.title === 'Mind Mapping') {
    const nodes = data.nodes || [];
    const edges = data.edges || [];

    // Calculate bounding box
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    if (nodes.length === 0) {
        minX = 0; minY = 0; maxX = 800; maxY = 600;
    } else {
        nodes.forEach(n => {
            if (n.position.x < minX) minX = n.position.x;
            if (n.position.y < minY) minY = n.position.y;
            // Est width/height if not present
            const w = n.style?.width ? parseInt(n.style.width) : (n.type === 'imageNode' ? 200 : 150);
            const h = n.style?.height ? parseInt(n.style.height) : (n.type === 'imageNode' ? 150 : 50);
            if (n.position.x + w > maxX) maxX = n.position.x + w;
            if (n.position.y + h > maxY) maxY = n.position.y + h;
        });
    }

    const padding = 50;
    const width = Math.max(800, maxX - minX + padding * 2);
    const height = Math.max(600, maxY - minY + padding * 2);

    const getNormPos = (pos) => ({
        x: pos.x - minX + padding,
        y: pos.y - minY + padding + 80 // Shift down 80px to avoid title overlap
    });

    return (
        <div ref={innerRef} style={{ ...baseStyle, width: `${width}px`, height: `${height}px`, padding: '0', position: 'relative', overflow: 'hidden', backgroundColor: '#f8fafc' }}>
            <h1 style={{ ...h1Style, position: 'absolute', top: '20px', left: '20px', zIndex: 50, backgroundColor: 'rgba(255,255,255,0.8)', padding: '10px' }}>{template.title}</h1>
            
            {/* Edges Layer */}
            <svg style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', pointerEvents: 'none', zIndex: 0 }}>
                {edges.map(edge => {
                    const source = nodes.find(n => n.id === edge.source);
                    const target = nodes.find(n => n.id === edge.target);
                    if (!source || !target) return null;
                    
                    const sPos = getNormPos(source.position);
                    const tPos = getNormPos(target.position);
                    
                    // Simple estimation of center
                    const sW = source.style?.width ? parseInt(source.style.width) : (source.type === 'imageNode' ? 200 : 100); 
                    const sH = source.style?.height ? parseInt(source.style.height) : (source.type === 'imageNode' ? 150 : 40);
                    const tW = target.style?.width ? parseInt(target.style.width) : (target.type === 'imageNode' ? 200 : 100);
                    const tH = target.style?.height ? parseInt(target.style.height) : (target.type === 'imageNode' ? 150 : 40);

                    const x1 = sPos.x + sW/2;
                    const y1 = sPos.y + sH/2;
                    const x2 = tPos.x + tW/2;
                    const y2 = tPos.y + tH/2;
                    
                    // Draw Edge Label (Midpoint)
                    const midX = (x1 + x2) / 2;
                    const midY = (y1 + y2) / 2;

                    return (
                        <g key={edge.id}>
                            <path 
                               d={`M${x1},${y1} Q${(x1+x2)/2},${y1} ${x2},${y2}`} 
                               stroke={edge.style?.stroke || "#cbd5e1"} 
                               strokeWidth="2" 
                               fill="none" 
                            />
                        </g>
                    );
                })}
            </svg>
            
            {/* Edge Labels (HTML for easier text handling) */}
            {edges.map(edge => {
                 if (!edge.label) return null;
                 const source = nodes.find(n => n.id === edge.source);
                 const target = nodes.find(n => n.id === edge.target);
                 if (!source || !target) return null;

                 const sPos = getNormPos(source.position);
                 const tPos = getNormPos(target.position);
                 const sW = source.style?.width ? parseInt(source.style.width) : (source.type === 'imageNode' ? 200 : 100); 
                 const sH = source.style?.height ? parseInt(source.style.height) : (source.type === 'imageNode' ? 150 : 40);
                 const tW = target.style?.width ? parseInt(target.style.width) : (target.type === 'imageNode' ? 200 : 100);
                 const tH = target.style?.height ? parseInt(target.style.height) : (target.type === 'imageNode' ? 150 : 40);

                 const x1 = sPos.x + sW/2;
                 const y1 = sPos.y + sH/2;
                 const x2 = tPos.x + tW/2;
                 const y2 = tPos.y + tH/2;
                 const midX = (x1 + x2) / 2;
                 const midY = (y1 + y2) / 2;

                 return (
                     <div key={`lbl-${edge.id}`} style={{
                         position: 'absolute',
                         left: midX,
                         top: midY,
                         transform: 'translate(-50%, -50%)',
                         backgroundColor: 'white',
                         padding: '2px 6px',
                         borderRadius: '4px',
                         fontSize: '12px',
                         border: `1px solid ${edge.style?.stroke || '#cbd5e1'}`,
                         color: '#475569',
                         zIndex: 5
                     }}>
                         {edge.label}
                     </div>
                 );
            })}

            {nodes.map(node => {
                const pos = getNormPos(node.position);
                if (node.type === 'imageNode') {
                     // Robust width reading: check style.width (string px) -> default
                     const w = node.style?.width ? node.style.width : '200px';
                     const h = node.style?.height ? node.style.height : '150px';

                     return (
                        <div key={node.id} style={{
                            position: 'absolute',
                            left: pos.x,
                            top: pos.y,
                            width: String(w).endsWith('px') ? w : `${w}px`,
                            height: String(h).endsWith('px') ? h : `${h}px`,
                            border: '1px solid #e2e8f0',
                            borderRadius: '8px',
                            overflow: 'hidden',
                            backgroundColor: 'white',
                            boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
                            zIndex: 10
                        }}>
                             <img src={node.data.src} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                        </div>
                     );
                }
                // Text Node
                return (
                    <div key={node.id} style={{
                        position: 'absolute',
                        left: pos.x,
                        top: pos.y,
                        padding: '8px 16px',
                        borderRadius: '9999px',
                        border: `2px solid ${node.data.color || '#e5e7eb'}`,
                        backgroundColor: node.data.bgColor || 'white',
                        boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
                        minWidth: '100px',
                        textAlign: 'center',
                        fontSize: node.data.fontSize || '14px',
                        fontWeight: node.data.isBold ? 'bold' : 'normal',
                        color: '#1f2937',
                        zIndex: 10
                    }}>
                        {node.data.label}
                    </div>
                );
            })}
             <div style={{ position: 'absolute', bottom: '20px', width: '100%', textAlign: 'center', fontSize: '14px', color: colors.gray400 }}>
                Generated by Design Thinking Platform
            </div>
        </div>
    );
  }

  // --- Default List Layout ---
  const sections = template.content && typeof template.content === 'string'
    ? JSON.parse(template.content).sections
    : (template.content?.sections || []);

  return (
    <div ref={innerRef} style={{ ...baseStyle, padding: '48px' }}>
      <h1 style={h1Style}>{template.title}</h1>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
        {sections.map(section => (
          <div key={section.id} style={cardStyle}>
            <h3 style={h3Style}>{section.label}</h3>
            <div style={{ ...pStyle, lineHeight: '1.625' }}>
              {data[section.id] || <span style={{ fontStyle: 'italic', color: colors.gray400 }}>No content</span>}
            </div>
          </div>
        ))}
      </div>
      <div style={{ marginTop: '48px', paddingTop: '16px', borderTop: `1px solid ${colors.gray200}`, textAlign: 'center', fontSize: '14px', color: colors.gray400 }}>
        Generated by Design Thinking Platform
      </div>
    </div>
  );

};

export default VisualRenderer;
